---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
  metrics:
    enabled: true
  coverage:
    enabled: false
languages:

exclude_paths:
  - "fuzz/**/*"
  - "fuzz/*"
  - "scripts/**/*"
  - "scripts/*"
  - "**.md"
